### ISSUE TITLE
Kompilieren?

### ISSUE THREAD

**Issue by iobFan** [hh-cm/GetAdmin#1]
Hallo Christian,
wie kann ich das getAdmin zu einem lauffähigen Programm kompilieren?

Danke vorab.

**Comment by hh-cm** [comment]
Woran hapert es denn?
Ich konnte das Programm mit Delphi 10.4.x und 11 kompilieren.

**Comment by hh-cm** [comment]
Ich habe auch im Release mal eine lauffähige Version hinzugefügt. (GetAdmin.zip)
